services:
  - type: web
    name: datazone-web-api
    env: docker
    dockerfilePath: ./DataZone-web-api/Dockerfile
    startCommand: ""  # Optional: command to start the service
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Development
    disk:
      name: shared-data
      mountPath: /shared-data
      sizeGB: 10

  - type: web
    name: pg-admin-ui
    env: docker
    image: dpage/pgadmin4
    envVars:
      - key: PGADMIN_DEFAULT_EMAIL
        value: yosephhabtamu5@gmail.com
      - key: PGADMIN_DEFAULT_PASSWORD
        value: 123456

  - type: worker
    name: datazone-analytics-server-exploratory
    env: docker
    dockerfilePath: ./DataZone-analytics-server/Dockerfile
    startCommand: poetry run python main.py exploratory
    disk:
      name: shared-data
      mountPath: /shared-data
      sizeGB: 10

  - type: worker
    name: datazone-analytics-server-regression
    env: docker
    dockerfilePath: ./DataZone-analytics-server/Dockerfile
    startCommand: poetry run python main.py regression
    disk:
      name: shared-data
      mountPath: /shared-data
      sizeGB: 10

  - type: worker
    name: datazone-analytics-server-visualization
    env: docker
    dockerfilePath: ./DataZone-analytics-server/Dockerfile
    startCommand: poetry run python main.py visualization
    disk:
      name: shared-data
      mountPath: /shared-data
      sizeGB: 10

  - type: web
    name: datazone-message
    env: docker
    dockerfilePath: ./rabbitmq/Dockerfile

databases:
  - name: datazone
    engine: postgres
    postgresMajorVersion: "15" 
    databaseName: datazone
    user: postgres

    plan: free
envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: datazone
      property: "postgresql://postgres:123456@host:5432/datazone"