services:
  - type: web
    name: datazone-web-api
    env: docker
    dockerfilePath: ./DataZone-web-api/Dockerfile
    startCommand: ""  # Optional: command to start the service
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Development
    disk:
      name: shared-data
      mountPath: /shared-data
      sizeGB: 10

  - type: worker
    name: datazone-analytics-server-exploratory
    env: docker
    dockerfilePath: ./DataZone-analytics-server/Dockerfile
    startCommand: poetry run python main.py exploratory
    disk:
      name: shared-data
      mountPath: /shared-data
      sizeGB: 10

  - type: worker
    name: datazone-analytics-server-regression
    env: docker
    dockerfilePath: ./DataZone-analytics-server/Dockerfile
    startCommand: poetry run python main.py regression
    disk:
      name: shared-data
      mountPath: /shared-data
      sizeGB: 10

  - type: worker
    name: datazone-analytics-server-visualization
    env: docker
    dockerfilePath: ./DataZone-analytics-server/Dockerfile
    startCommand: poetry run python main.py visualization
    disk:
      name: shared-data
      mountPath: /shared-data
      sizeGB: 10

  - type: web
    name: datazone-message
    env: docker
    dockerfilePath: ./rabbitmq/Dockerfile

databases:
  - name: datazone
    postgresMajorVersion: "15" 
    databaseName: datazone
    user: postgres
    plan: free