services:
  - type: web
    name: datazone-web-api
    env: docker
    dockerfilePath: ./DataZone-web-api/Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Development
    disk:
      name: shared-data
      mountPath: /shared-data
      sizeGB: 10

  - type: web
    name: datazone-analytics-server-exploratory
    env: docker
    dockerfilePath: ./DataZone-analytics-server/Depl-instances/Dockerfile-exploratory
    disk:
      name: shared-data
      mountPath: /shared-data
      sizeGB: 10

  - type: web
    name: datazone-analytics-server-regression
    env: docker
    dockerfilePath: ./DataZone-analytics-server/Depl-instances/Dockerfile-regression
    disk:
      name: shared-data
      mountPath: /shared-data
      sizeGB: 10

  - type: web
    name: datazone-analytics-server-visualization
    env: docker
    dockerfilePath: ./DataZone-analytics-server/Depl-instances/Dockerfile-visualization
    disk:
      name: shared-data
      mountPath: /shared-data
      sizeGB: 10

  - type: web
    name: datazone-message
    env: docker
    dockerfilePath: ./rabbitmq/Dockerfile

databases:
  - name: datazone
    postgresMajorVersion: "15" 
    databaseName: datazone